my first try in blog
ES-Bootcamp/ESB-Blog pull request #1
Opened 2020-10-20 16:44 UTC by zinou-11y

2020-10-20 17:01 UTC, celyes requested changes
Utiliser un CDN : 

https://cdn.jsdelivr.net/npm/font-awesome@4.7.0/css/font-awesome.min.css

2020-10-24 09:28 UTC, zinou-11y commented
close my first try

2020-10-25 15:22 UTC, celyes requested changes
vous pouvez déployer les pages sur un service d'hébergement afin que je puisse voir le problème en direct

2020-10-25 15:22 UTC, celyes commented on css/style.css
> +}
supprimer toutes les lignes sans contenu

2020-10-27 15:10 UTC, closed without merging